apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: totoro-books-secret-store
  namespace: totoro-books
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-credentials-totoro-books
            key: key.json
      projectID: totoro-books
