apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secret-manager-credentials
spec:
  provider:
    gcpsm:
      projectID: "totoro-ox-k3s-cluster"
      auth:
        secretRef:
          name: gcp-cluster-secret-manager-credentials
          key: credentials.json
          namespace: external-secrets
