apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    argocd.argoproj.io/instance: external-secrets-totoro-ox-k3-cluster
  name: cloudflare-api-token
  namespace: certmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-totoro-cluster-secret-store
  target:
    name: cloudflare-api-token
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflare-api-token-totoro-ox
        version: latest
