apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    argocd.argoproj.io/instance: external-secrets-totoro-ox-k3-cluster
  name: cloudflare-api-token
  namespace: certmanager
spec:
  data:
    - remoteRef:
        key: cloudflare-api-token-totoro-ox
        version: latest
      secretKey: CLOUDFLARE_API_TOKEN
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gpc-cluster-secret-store
  target:
    name: cloudflare-api-token
