apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: certmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gpc-cluster-secret-store 
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
  data:
    - secretKey: CLOUDFLARE_API_TOKEN 
      remoteRef:
        key: cloudflare-api-token
        version: latest

