apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: wordpress-ms-prod-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-credentials
            key: key.json
      projectID: wordpress-ms-444322
