apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: totoro-media-external-secrets
  namespace: totoro-media
spec:
  secretStoreRef:
    kind: SecretStore
    name: totoro-media-secret-store
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: db_host
        version: latest
    - secretKey: DB_PORT
      remoteRef:
        key: db_port
        version: latest
    - secretKey: DB_USER
      remoteRef:
        key: db_user
        version: latest
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db_password
        version: latest
    - secretKey: DB_NAME
      remoteRef:
        key: db_name
        version: latest
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: google_client_id
        version: latest
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: google_client_secret
        version: latest
    - secretKey: GOOGLE_REDIRECT_URL
      remoteRef:
        key: google_redirect_url
        version: latest
    - secretKey: R2_ACCOUNT_ID
      remoteRef:
        key: r2_account_id
        version: latest
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: r2_access_key_id
        version: latest
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: r2_secret_access_key
        version: latest
    - secretKey: R2_BUCKET
      remoteRef:
        key: r2_bucket
        version: latest
    - secretKey: ALLOWED_EMAILS
      remoteRef:
        key: allowed_emails
        version: latest
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: admin_email
        version: latest
  refreshInterval: 1h
  target:
    name: totoro-media-secrets
    creationPolicy: Owner
    deletionPolicy: Retain

