apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: totoro-finance-external-secrets
  namespace: totoro-finance
spec:
  secretStoreRef:
    kind: SecretStore
    name: totoro-finance-secret-store
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: db_host
        version: latest
    - secretKey: DB_PORT
      remoteRef:
        key: db_port
        version: latest
    - secretKey: DB_USER
      remoteRef:
        key: db_user
        version: latest
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db_password
        version: latest
    - secretKey: DB_NAME
      remoteRef:
        key: db_name
        version: latest
    - secretKey: TOKEN_ENC_KEY
      remoteRef:
        key: token_enc_key
        version: latest
    - secretKey: SUPERADMIN_NAME
      remoteRef:
        key: superadmin_name
        version: latest
    - secretKey: SUPERADMIN_EMAIL
      remoteRef:
        key: superadmin_email
        version: latest
    - secretKey: SUPERADMIN_PASSWORD
      remoteRef:
        key: superadmin_password
        version: latest
    - secretKey: MONZO_CLIENT_ID
      remoteRef:
        key: monzo_client_id
        version: latest
    - secretKey: MONZO_CLIENT_SECRET
      remoteRef:
        key: monzo_client_secret
        version: latest
    - secretKey: MONZO_REDIRECT_URI
      remoteRef:
        key: monzo_redirect_uri
        version: latest
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: google_client_id
        version: latest
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: google_client_secret
        version: latest
  refreshInterval: 1h
  target:
    name: totoro-finance-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
