apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-ms-external-secrets
  namespace: wordpress-ms-prod
spec:
  secretStoreRef:
    kind: SecretStore
    name: wordpress-ms-prod-secret-store
  data:
    - secretKey: WORDPRESS_DB_HOST
      remoteRef:
        key: wordpress_db_host
        version: latest
    - secretKey: WORDPRESS_DB_NAME
      remoteRef:
        key: wordpress_db_name
        version: latest
    - secretKey: WORDPRESS_DB_USER
      remoteRef:
        key: wordpress_db_user
        version: latest
    - secretKey: WORDPRESS_DB_PASSWORD
      remoteRef:
        key: wordpress_db_password
        version: latest
    - secretKey: WORDPRESS_MULTISITE
      remoteRef:
        key: wordpress_multisite
        version: latest
    - secretKey: WORDPRESS_SUBDOMAIN_INSTALL
      remoteRef:
        key: wordpress_subdomain_install
        version: latest
    - secretKey: WORDPRESS_DOMAIN
      remoteRef:
        key: wordpress_domain
        version: latest
    - secretKey: WORDPRESS_PATH
      remoteRef:
        key: wordpress_path
        version: latest
    - secretKey: WORDPRESS_NETWORK_TITLE
      remoteRef:
        key: wordpress_network_title
        version: latest
    - secretKey: WORDPRESS_ENV
      remoteRef:
        key: wordpress_env
        version: latest
    - secretKey: WORDPRESS_DEBUG
      remoteRef:
        key: wordpress_debug
        version: latest
    - secretKey: WORDPRESS_AUTH_KEY
      remoteRef:
        key: wordpress_auth_key
        version: latest
    - secretKey: WORDPRESS_SECURE_AUTH_KEY
      remoteRef:
        key: wordpress_secure_auth_key
        version: latest
    - secretKey: WORDPRESS_LOGGED_IN_KEY
      remoteRef:
        key: wordpress_logged_in_key
        version: latest
    - secretKey: WORDPRESS_NONCE_KEY
      remoteRef:
        key: wordpress_nonce_key
        version: latest
    - secretKey: WORDPRESS_AUTH_SALT
      remoteRef:
        key: wordpress_auth_salt
        version: latest
    - secretKey: WORDPRESS_SECURE_AUTH_SALT
      remoteRef:
        key: wordpress_secure_auth_salt
        version: latest
    - secretKey: WORDPRESS_LOGGED_IN_SALT
      remoteRef:
        key: wordpress_logged_in_salt
        version: latest
    - secretKey: WORDPRESS_NONCE_SALT
      remoteRef:
        key: wordpress_nonce_salt
        version: latest
    - secretKey: WORDPRESS_ADMIN_USER
      remoteRef:
        key: wordpress_admin_user
        version: latest
    - secretKey: WORDPRESS_ADMIN_PASSWORD
      remoteRef:
        key: wordpress_admin_password
        version: latest
    - secretKey: WORDPRESS_ADMIN_EMAIL
      remoteRef:
        key: wordpress_admin_email
        version: latest
    - secretKey: S3_UPLOADS_BUCKET
      remoteRef:
        key: wordpress_s3_uploads_bucket
        version: latest
    - secretKey: S3_UPLOADS_REGION
      remoteRef:
        key: wordpress_s3_uploads_region
        version: latest
    - secretKey: S3_UPLOADS_KEY
      remoteRef:
        key: wordpress_s3_uploads_key
        version: latest
    - secretKey: S3_UPLOADS_SECRET
      remoteRef:
        key: wordpress_s3_uploads_secret
        version: latest
  refreshInterval: 1h
  target:
    name: wordpress-ms-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
