apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-external-secrets
  namespace: wordpress-ms-prod
spec:
  secretStoreRef:
    kind: SecretStore
    name: wordpress-ms-prod-secret-store
  data:
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: mysql_database
        version: latest
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: mysql_password
        version: latest
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: mysql_root_password
        version: latest
    - secretKey: MYSQL_USER
      remoteRef:
        key: mysql_user
        version: latest
  refreshInterval: 1h
  target:
    name: mariadb-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
