apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-ms-external-secrets
  namespace: wordpress-ms-prod
spec:
  secretStoreRef:
    kind: SecretStore  # Reference to the SecretStore in namespace
    name: wordpress-ms-prod-secret-store  # name of SecretStore
  data:
    - secretKey: WORDPRESS_ADMIN_EMAIL
      remoteRef:
        key: wordpress_admin_email
        version: latest
    - secretKey: WORDPRESS_ADMIN_PASSWORD
      remoteRef:
        key: wordpress_admin_password
        version: latest
    - secretKey: WORDPRESS_DB_HOST
      remoteRef:
        key: wordpress_db_host
        version: latest
  refreshInterval: 1h
  target:
    name: wordpress-ms-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
