apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-origin-secret
  namespace: wordpress-ms-prod
spec:
  secretStoreRef:
    kind: SecretStore
    name: wordpress-ms-prod-secret-store
  refreshInterval: 1h
  target:
    name: cloudflare-origin-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .cloudflare-origin-cert }}"
        tls.key: "{{ .cloudflare-origin-key }}"
  data:
    - secretKey: CLOUDFLARE_ORIGIN_CERT
      remoteRef:
        key: cloudflare_origin_cert
        version: latest
    - secretKey: CLOUDFLARE_ORIGIN_KEY
      remoteRef:
        key: cloudflare_origin_key
        version: latest
