apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: wordpress-ms-prod-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-credentials-wordpress-ms-prod
            key: key.json
      projectID: wordpress-ms-prod-444322
