apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: wordpress-ms-prod-secret-store
  namespace: wordpress-ms-prod
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-credentials-wordpress-ms
            kind: ClusterSecretStore
            key: key.json
      projectID: wordpress-ms-prod-444322
